### PR TITLE
Show error message if a config file is incorrect

### LINKED ISSUE #769: If a config file is incorrect the application silently dies
If a config file is incorrect the application silently dies when starting it.

### PR DESCRIPTION
**Pull request by ErikMogensen**
Fixes #769 

Shows one or two error messages if a config file is incorrect. The application still dies after that.

### CODE REVIEW

File: src/ServiceBusExplorer/Forms/MainForm.cs [hunk 1]
```diff
@@ -4041,7 +4041,14 @@ private void SetTitle(string prefix)
         #region Public Static Methods
         public static void StaticWriteToLog(string message, bool async = true)
         {
-            mainSingletonMainForm.WriteToLog(message);
+            if(null != mainSingletonMainForm)
```
Comment (SeanFeldman) [inline src/ServiceBusExplorer/Forms/MainForm.cs:4044]: Always found this notation awkward to read.
If you’re concerned about accidental null assignment, there’s a more readable way.

```suggestion
            if(mainSingletonMainForm is not null)
```

**Review by SeanFeldman — APPROVED** [review]

File: src/ServiceBusExplorer/Forms/MainForm.cs (hunk 1 above)
Comment (SeanFeldman) [reply src/ServiceBusExplorer/Forms/MainForm.cs]: Will need to revert. Or bump C# language version.

Comment (ErikMogensen) [reply src/ServiceBusExplorer/Forms/MainForm.cs]: Sadly we are stuck on 7.3 as long as we are using .Net Framework. https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version.
