### PR TITLE
Fix copying behavior of properties when resubmitting messages

### LINKED ISSUE #344: When resubmitting one or more messages from the deadletter subqueue the deadletter properties are kept
I would say that the excepted behavior would be that the deadletter properties are removed when a message is resubmitted from the deadletter subqueue. In fact there is code in MessageForm.cs for removing these properties. 

I think this behavior has changed. My guess is that there has been a change is the Service Bus SDK or the service that previously filtered out those properties when sending a message. 

This may be the cause for inability to resubmit messages in issue #195.

### PR DESCRIPTION
**Pull request by gabrielgt**
Fixes #344

When resubmitting several messages in batch mode, properties should be copied when cloning. But when resubmitting only one message, properties should not, because the user can choose what properties he wants to copy through Message Custom Properties GroupBox.

   image

So, clone depends on resubmitting one or more messages.
In any case, properties with name "DeadLetterReason", "DeadLetterErrorDescription" and "NServiceBus.Transport.Recovery", should never be copied.

Issue #344 should be solved with this PR.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-PullRequest0370.119.build.586 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/26489182) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/9384058b5f by @gabrielgt)

**Comment by paolosalvatori** [comment]
Hi @gabrielgt I approved the PR, but it has conflicts that must be resolved.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-develop-properties.59.build.657 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/31591247) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/039ba3d89d by @gabrielgt)

**Comment by gabrielgt** [comment]
Hi @paolosalvatori, I have resolved the conflicts. Sorry for the delay.

**Comment by SeanFeldman** [comment]
:white_check_mark: [Build ServiceBusExplorer 4.2.0-develop-properties.79.build.730 completed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36304218) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/a6b294cfd8 by @gabrielgt)

**Comment by gabrielgt** [comment]
I have resolved the conflicts again, please review the PR.

File: src/Common/Helpers/Constants.cs [hunk 1]
```diff
@@ -87,5 +87,6 @@ public static class Constants
         public static readonly Type MessageType = typeof(BrokeredMessage);
         public static readonly Type GuidType = typeof(Guid);
         public static readonly Type ObjectType = typeof(object);
+        public static readonly List<string> AlwaysOmittedProperties = new List<string> {"deadletterreason", "deadlettererrordescription", "nservicebus.transport.recovery"};
```
Comment (SeanFeldman) [inline src/Common/Helpers/Constants.cs:90]: I'm on a fence about this. When someone else adds a property to be excluded and they copy the property here, they have to remember to lower case it or else it won't work.
I'd rather see headers used as they are defined (provided).

File: src/Common/Helpers/BrokeredMessageExtensions.cs [hunk 2]
```diff
@@ -61,34 +62,39 @@ public static BrokeredMessage Clone(this BrokeredMessage message, Stream stream)
...
-            foreach (var header in originalMessage.Properties)
+            if (!omitAllProperties)
             {
-                // Recovery header should not be included
-                if (header.Key != "NServiceBus.Transport.Recovery")
-                {
-                    message.Properties[header.Key] = header.Value;
-                }
+                // Copy all custom properties
+                var propertiesToCopy = originalMessage.Properties.Where(h => !Constants.AlwaysOmittedProperties.Contains(h.Key.ToLower()));
```
Comment (SeanFeldman) [inline src/Common/Helpers/BrokeredMessageExtensions.cs:96]: We'd be safer to compare using `StringComparer.InvariantCultureIgnoreCase`. That way there's no need for special treatment neither of the excluded header values nor all message property names.

**Review by SeanFeldman — CHANGES_REQUESTED** [review]

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 4.2.0-develop-properties.80.build.731 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36322382) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/af38ea9de4 by @)

File: src/Common/Helpers/Constants.cs (hunk 1 above)
Comment (gabrielgt) [reply src/Common/Helpers/Constants.cs]: I agree. Changed to pascal case.

File: src/Common/Helpers/BrokeredMessageExtensions.cs (hunk 2 above)
Comment (gabrielgt) [reply src/Common/Helpers/BrokeredMessageExtensions.cs]: Changed for a comparison with InvariantCultureIgnoreCase in BrokeredMessageExtensions.cs and MessageForm.cs.

**Comment by SeanFeldman** [comment]
:x: [Build ServiceBusExplorer 4.2.0-develop-properties.80.build.732 failed](https://ci.appveyor.com/project/seanfeldman/servicebusexplorer/builds/36322437) (commit https://github.com/paolosalvatori/ServiceBusExplorer/commit/af38ea9de4 by @)

**Comment by SeanFeldman** [comment]
@gabrielgt the build is failing but doesn't seem like it's the change in this PR. I'll look into that tomorrow as I'd like to include this fix in 5.0.0.

**Comment by paolosalvatori** [comment]
Hi @SeanFeldman does the build succeed now? Can I proceed and approve this PR? Thanks

**Comment by SeanFeldman** [comment]
@paolosalvatori, it doesn't, and I'm confused why that's the case. It builds fine locally.

@gabrielgt, do you mind to open an alternative PR to see if that fixes it? Let's try fixing the PR build so that it can be included in the v5 release.

**Comment by gabrielgt** [comment]
@SeanFeldman did it, and it worked!! 😲

**Review by ErikMogensen — APPROVED** [review]
Nice!

**Review by SeanFeldman — APPROVED** [review]

**Comment by paolosalvatori** [comment]
Thanks folks :)
